spring:
  datasource:
    url: jdbc:mysql://localhost:3306/momsitter?characterEncoding=UTF-8&serverTimezone=UTC

    username: momsitter
    password: momsitter
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8080


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: momsitter-secret-key-very-secure
  expiration: 3600000 # 1시간 (밀리초 단위)